sylius_ui:
    events:
        sylius.shop.layout.footer.grid:
            blocks:
                before_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 20
                    context:
                        event: sylius.shop.layout.before_footer
                plus:
                    template: "@SyliusShop/Layout/Footer/Grid/_plus.html.twig"
                    priority: 30
                your_store:
                    template: "@SyliusShop/Layout/Footer/Grid/_your_store.html.twig"
                    priority: 25
                customer_care:
                    template: "@SyliusShop/Layout/Footer/Grid/_customer_care.html.twig"
                    priority: 45
                payment_methods:
                    template: "@SyliusShop/Layout/Footer/Grid/_payment_methods.html.twig"
                    priority: 10
                    
        sylius.shop.homepage:
            blocks:
                banner:
                    template: "@SyliusShop/Homepage/_banner.html.twig"
                    priority: 60
                latest_products:
                    template: "@SyliusShop/Homepage/_latestProducts.html.twig"
                    priority: 50
                latest_products_carousel:
                    template: "@SyliusShop/Homepage/_latestProductsCarousel.html.twig"
                    priority: 40
                    enabled: false
                newsletter:
                    template: "@SyliusShop/Homepage/_newsletter.html.twig"
                    priority: 30
                    enabled: false
                products_grid:
                    template: "@SyliusShop/Homepage/_productsGrid.html.twig"
                    priority: 20
                    enabled: false
                about_us:
                    template: "@SyliusShop/Homepage/_aboutUs.html.twig"
                    priority: 10
                    enabled: false
                    
        sylius.shop.taxon.header:
            blocks:
                breadcrumb:
                    template: "@SyliusShop/Taxon/_breadcrumb.html.twig"
                    priority: 20
                before_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.taxon.header.before
                header:
                    template: "@SyliusShop/Taxon/Header/_content.html.twig"
                    priority: 10
                after_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.taxon.header.after            
